"""Medical Claim Management Service (Phase 33).

Orchestrates:
- Claim construction and line item validation
- Coverage validation and pre-authorization verification
- Idempotent claim submission to external payer clearinghouses
- Real-time status polling and transition enforcement
"""

from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from typing import List, Optional, Tuple

from app.core.config import settings
from app.core.exceptions import (
    AuthorizationNotFoundException,
    ClaimAlreadySubmittedException,
    ClaimAuthorizationMismatchException,
    ClaimCoverageMismatchException,
    ClaimDisabledException,
    ClaimNotFoundException,
    ClaimSubmissionFailedException,
    ClaimSubmissionUnknownException,
    ClaimValidationFailedException,
    InsuranceNotFoundException,
)
from app.integrations.payers.base import PayerProvider
from app.integrations.payers.providers.mock import MockPayerProvider
from app.repositories.authorization_repository import AuthorizationRepository
from app.repositories.claim_repository import ClaimRepository
from app.repositories.insurance_repository import InsuranceRepository
from app.schemas.authorization import PreAuthorizationStatus
from app.schemas.claim import (
    ClaimCreateRequest,
    ClaimRecord,
    ClaimResponse,
    ClaimStatus,
    ClaimSubmitRequest,
)
from app.schemas.insurance import CoverageStatus
from app.schemas.user import AuthenticatedUserContext
from app.services.insurance_validation_service import InsuranceValidationService
from app.services.payer_authorization_service import PayerAuthorizationService

logger = logging.getLogger(__name__)


class ClaimService:
    """Service managing medical claim lifecycle and submission."""

    def __init__(
        self,
        insurance_repo: Optional[InsuranceRepository] = None,
        claim_repo: Optional[ClaimRepository] = None,
        auth_repo: Optional[AuthorizationRepository] = None,
        provider: Optional[PayerProvider] = None,
    ) -> None:
        self.insurance_repo = insurance_repo or InsuranceRepository()
        self.claim_repo = claim_repo or ClaimRepository()
        self.auth_repo = auth_repo or AuthorizationRepository()
        self.provider = provider or MockPayerProvider()

    def _ensure_enabled(self) -> None:
        if not settings.INSURANCE_ENABLED or not settings.CLAIMS_ENABLED:
            raise ClaimDisabledException("Insurance claims subsystem is disabled.")

    def create_claim(
        self,
        caller: AuthenticatedUserContext,
        payload: ClaimCreateRequest,
    ) -> ClaimResponse:
        """Create a draft claim after strict line item and coverage validation."""
        self._ensure_enabled()

        coverage = self.insurance_repo.get(payload.coverage_id)
        if not coverage:
            raise InsuranceNotFoundException(f"Insurance coverage {payload.coverage_id} not found.")

        if coverage.patient_id != payload.patient_id:
            raise ClaimCoverageMismatchException("Coverage record does not match patient ID specified on claim.")

        if coverage.status in (CoverageStatus.TERMINATED, CoverageStatus.EXPIRED):
            raise ClaimCoverageMismatchException(
                f"Cannot file claim against {coverage.status.value} insurance policy."
            )

        # Validate Pre-Authorization if provided
        if payload.authorization_id:
            preauth = self.auth_repo.get(payload.authorization_id)
            if not preauth:
                raise AuthorizationNotFoundException(f"Referenced authorization {payload.authorization_id} not found.")
            if preauth.status != PreAuthorizationStatus.APPROVED:
                raise ClaimAuthorizationMismatchException(
                    f"Referenced pre-authorization {payload.authorization_id} is in status {preauth.status.value}, not APPROVED."
                )

        claim_id = f"clm_{uuid.uuid4().hex[:12]}"
        items, total_amount = InsuranceValidationService.calculate_claim_totals(
            items=payload.items,
            claim_id=claim_id,
            default_currency=payload.currency.upper(),
        )

        record = ClaimRecord(
            id=claim_id,
            claim_number="",  # Auto-generated by repository
            patient_id=payload.patient_id,
            coverage_id=coverage.id,
            payer_id=coverage.payer_id,
            organization_id=payload.organization_id,
            facility_id=payload.facility_id,
            clinician_id=payload.clinician_id,
            invoice_id=payload.invoice_id,
            authorization_id=payload.authorization_id,
            claim_type=payload.claim_type,
            status=ClaimStatus.DRAFT,
            total_amount_in_minor_units=total_amount,
            currency=payload.currency.upper(),
            items=items,
            diagnosis_codes=payload.diagnosis_codes,
            notes=payload.notes,
        )

        PayerAuthorizationService.authorize_claim_access(caller, record, action="create")
        created = self.claim_repo.create(record)

        logger.info(
            f"Created claim draft: id={created.id}, number={created.claim_number}, "
            f"patient={created.patient_id}, amount={created.total_amount_in_minor_units} {created.currency}"
        )
        return created.to_response()

    async def submit_claim(
        self,
        caller: AuthenticatedUserContext,
        claim_id: str,
        payload: Optional[ClaimSubmitRequest] = None,
    ) -> ClaimResponse:
        """Submit claim to external payer clearinghouse."""
        self._ensure_enabled()
        if not settings.CLAIM_SUBMISSION_ENABLED:
            raise ClaimDisabledException("Claim submission is currently disabled.")

        record = self.claim_repo.get(claim_id)
        if not record:
            raise ClaimNotFoundException(f"Claim {claim_id} not found.")

        PayerAuthorizationService.authorize_claim_access(caller, record, action="submit")

        # Idempotency check: if caller provided idempotency_key, check for previous run
        idemp_key = payload.idempotency_key if payload else None
        if idemp_key:
            existing = self.claim_repo.get_by_idempotency_key(idemp_key)
            if existing and existing.status in (
                ClaimStatus.SUBMITTED,
                ClaimStatus.RECEIVED,
                ClaimStatus.APPROVED,
                ClaimStatus.PAID,
            ):
                logger.info(f"Returning previously submitted claim for idempotency key {idemp_key}")
                return existing.to_response()
            record.idempotency_key = idemp_key

        if record.status in (ClaimStatus.SUBMITTED, ClaimStatus.RECEIVED, ClaimStatus.APPROVED, ClaimStatus.PAID):
            raise ClaimAlreadySubmittedException(f"Claim {claim_id} is already in state {record.status.value}")

        InsuranceValidationService.validate_claim_transition(record.status, ClaimStatus.SUBMITTED)
        record.status = ClaimStatus.SUBMITTED
        record.submission_timestamp = datetime.now(timezone.utc)

        try:
            prov_res = await self.provider.submit_claim(record)
        except Exception as exc:
            logger.error(f"Payer gateway failed during claim submission: {exc}")
            record.status = ClaimStatus.FAILED
            self.claim_repo.update(record)
            raise ClaimSubmissionFailedException(f"Claim submission failed at gateway: {exc}")

        if prov_res.status == ClaimStatus.UNKNOWN:
            record.status = ClaimStatus.UNKNOWN
            record.notes = f"{record.notes or ''}\nSubmission returned ambiguous result; reconciliation required."
            self.claim_repo.update(record)
            raise ClaimSubmissionUnknownException("Claim submission result is ambiguous; reconciliation required.")

        if prov_res.success:
            record.status = prov_res.status
            record.provider_claim_reference = prov_res.provider_claim_reference
            record.raw_response = prov_res.raw_response
        else:
            record.status = ClaimStatus.FAILED
            record.denial_reason = prov_res.error_message

        updated = self.claim_repo.update(record)
        logger.info(
            f"Claim submission completed: id={updated.id}, number={updated.claim_number}, "
            f"status={updated.status.value}, ref={updated.provider_claim_reference}"
        )
        return updated.to_response()

    def get_claim(
        self,
        caller: AuthenticatedUserContext,
        claim_id: str,
    ) -> ClaimResponse:
        """Fetch claim details by ID."""
        self._ensure_enabled()
        record = self.claim_repo.get(claim_id)
        if not record:
            raise ClaimNotFoundException(f"Claim {claim_id} not found.")

        PayerAuthorizationService.authorize_claim_access(caller, record, action="read")
        return record.to_response()

    async def sync_claim_status(
        self,
        caller: AuthenticatedUserContext,
        claim_id: str,
    ) -> ClaimResponse:
        """Sync live claim status from payer clearinghouse."""
        self._ensure_enabled()
        record = self.claim_repo.get(claim_id)
        if not record:
            raise ClaimNotFoundException(f"Claim {claim_id} not found.")

        PayerAuthorizationService.authorize_claim_access(caller, record, action="sync_status")

        if record.provider_claim_reference:
            prov_res = await self.provider.get_claim_status(record.provider_claim_reference)
            if prov_res.success and prov_res.status != ClaimStatus.UNKNOWN:
                InsuranceValidationService.validate_claim_transition(record.status, prov_res.status)
                record.status = prov_res.status
                self.claim_repo.update(record)

        return record.to_response()

    def list_patient_claims(
        self,
        caller: AuthenticatedUserContext,
        patient_id: str,
        status: Optional[ClaimStatus] = None,
        limit: int = 50,
        offset: int = 0,
    ) -> Tuple[List[ClaimResponse], int]:
        """List claims filed for a patient."""
        self._ensure_enabled()
        dummy_record = ClaimRecord(
            id="probe",
            claim_number="probe",
            patient_id=patient_id,
            coverage_id="probe",
            payer_id="probe",
            total_amount_in_minor_units=0,
        )
        PayerAuthorizationService.authorize_claim_access(caller, dummy_record, action="read")

        records, total = self.claim_repo.list_by_patient(patient_id, status=status, limit=limit, offset=offset)
        return [r.to_response() for r in records], total
