"""Explanation Service (Phase 47).

Constructs structured, audience-tailored explanations for system recommendations,
rules, and classifications without exposing internal model chain-of-thought.
"""

from __future__ import annotations

from datetime import datetime, timezone
import logging
from typing import Optional

from app.schemas.decisions import DecisionRecord, DecisionStatus, DecisionType
from app.schemas.explanations import ExplanationAudience, ExplanationResponse

logger = logging.getLogger(__name__)


class ExplanationService:
    """Generates traceable, safe explanations for clinical decision records."""

    def generate_explanation(
        self,
        decision: DecisionRecord,
        audience: ExplanationAudience = ExplanationAudience.CLINICIAN,
    ) -> ExplanationResponse:
        """Construct a structured explanation tailored to the requested audience."""
        # 1. Human oversight description
        if decision.status == DecisionStatus.APPROVED:
            oversight_str = "Approved by human clinician"
        elif decision.status == DecisionStatus.REJECTED:
            oversight_str = "Rejected by human clinician"
        elif decision.status == DecisionStatus.APPLIED:
            oversight_str = "Clinically approved and applied to workflow"
        elif decision.requires_human_oversight:
            oversight_str = "Pending mandatory clinical review"
        else:
            oversight_str = "Informational / No review mandatory"

        # 2. Input factors summary
        input_descriptions = [
            f"{ref.resource_type} (id: {ref.resource_id}, v{ref.version_number or 'current'})"
            for ref in decision.inputs
        ]
        if not input_descriptions and decision.resource_type and decision.resource_id:
            input_descriptions = [
                f"{decision.resource_type} (id: {decision.resource_id}, v{decision.resource_version or '1'})"
            ]

        # 3. Rule / Model reference
        if decision.rule_metadata and decision.rule_metadata.rule_set_id:
            rule_ref = f"Rule Set: {decision.rule_metadata.rule_set_id} v{decision.rule_metadata.rule_set_version or '1.0'}"
            if audience != ExplanationAudience.PATIENT and decision.rule_metadata.matched_rule_ids:
                rule_ref += f" [Matched: {', '.join(decision.rule_metadata.matched_rule_ids)}]"
        elif decision.model_metadata and decision.model_metadata.model_identifier:
            if audience == ExplanationAudience.PATIENT:
                rule_ref = "HealthSetu Clinical Intelligence Assistant"
            else:
                rule_ref = f"AI Provider: {decision.model_metadata.provider or 'internal'} ({decision.model_metadata.model_identifier})"
        else:
            rule_ref = f"System Service: {decision.source_service}"

        # 4. Audience-tailored text
        if audience == ExplanationAudience.PATIENT:
            headline = f"Health Assessment Summary ({decision.decision_type.value.replace('_', ' ').title()})"
            why_text = (
                "This assessment was generated by clinical support tools to assist your healthcare team. "
                "It is based on your recent health details and clinical checkups."
            )
            disclaimer = (
                "This information is an automated clinical aid for your healthcare providers. "
                "It is not a final medical diagnosis or prescription."
            )
        else:
            headline = f"Decision Trace: {decision.decision_type.value} [{decision.status.value}]"
            why_text = (
                f"Generated by {decision.source_service} with {len(decision.inputs)} input dependencies. "
                f"Result: {decision.output_payload}"
            )
            disclaimer = (
                "Clinical decision support output. Human oversight is authoritative; "
                "system output does not constitute autonomous medical practice."
            )

        confidence = decision.model_metadata.confidence if decision.model_metadata else None

        return ExplanationResponse(
            decision_id=decision.id,
            decision_type=decision.decision_type,
            audience=audience,
            headline=headline,
            why_generated=why_text,
            inputs_considered=input_descriptions,
            rules_or_model_used=rule_ref,
            human_oversight_status=oversight_str,
            is_current=decision.is_current,
            is_applied=(decision.status == DecisionStatus.APPLIED),
            evidence_references=[],
            confidence=confidence,
            generated_at=datetime.now(timezone.utc),
            disclaimer=disclaimer,
        )


explanation_service = ExplanationService()
