"""Pre-Authorization (Prior Auth) Service (Phase 33).

Orchestrates prior authorization drafting, validation, submission to payers, and status tracking.
CRITICAL SAFETY INVARIANTS:
- PRE-AUTHORIZATION ≠ CLINICAL AUTHORITY.
- APPROVED AUTHORIZATION DOES NOT GUARANTEE TREATMENT PERFORMANCE OR CLAIM PAYMENT.
- DO NOT AUTONOMOUSLY DETERMINE MEDICAL NECESSITY.
"""

from __future__ import annotations

import logging
import uuid
from typing import List, Optional, Tuple

from app.core.config import settings
from app.core.exceptions import (
    AuthorizationNotFoundException,
    AuthorizationSubmissionFailedException,
    InsuranceNotFoundException,
    PreAuthorizationDisabledException,
)
from app.integrations.payers.base import PayerProvider
from app.integrations.payers.providers.mock import MockPayerProvider
from app.repositories.authorization_repository import AuthorizationRepository
from app.repositories.insurance_repository import InsuranceRepository
from app.schemas.authorization import (
    PreAuthorizationCreate,
    PreAuthorizationRecord,
    PreAuthorizationResponse,
    PreAuthorizationStatus,
    PreAuthorizationSubmitRequest,
)
from app.schemas.user import AuthenticatedUserContext
from app.services.insurance_validation_service import InsuranceValidationService
from app.services.payer_authorization_service import PayerAuthorizationService

logger = logging.getLogger(__name__)


class PreAuthorizationService:
    """Service managing prior authorization workflows."""

    def __init__(
        self,
        insurance_repo: Optional[InsuranceRepository] = None,
        auth_repo: Optional[AuthorizationRepository] = None,
        provider: Optional[PayerProvider] = None,
    ) -> None:
        self.insurance_repo = insurance_repo or InsuranceRepository()
        self.auth_repo = auth_repo or AuthorizationRepository()
        self.provider = provider or MockPayerProvider()

    def _ensure_enabled(self) -> None:
        if not settings.INSURANCE_ENABLED or not settings.PREAUTHORIZATION_ENABLED:
            raise PreAuthorizationDisabledException("Pre-authorization subsystem is disabled.")

    def create_preauthorization(
        self,
        caller: AuthenticatedUserContext,
        payload: PreAuthorizationCreate,
    ) -> PreAuthorizationResponse:
        """Create draft pre-authorization request."""
        self._ensure_enabled()

        coverage = self.insurance_repo.get(payload.coverage_id)
        if not coverage:
            raise InsuranceNotFoundException(f"Coverage {payload.coverage_id} not found.")

        record = PreAuthorizationRecord(
            id=f"pauth_{uuid.uuid4().hex[:12]}",
            authorization_number="",  # Auto-generated by repository
            patient_id=payload.patient_id,
            coverage_id=coverage.id,
            payer_id=coverage.payer_id,
            facility_id=payload.facility_id,
            clinician_id=payload.clinician_id,
            appointment_id=payload.appointment_id,
            status=PreAuthorizationStatus.DRAFT,
            service_code=payload.service_code,
            service_description=payload.service_description,
            estimated_amount_in_minor_units=payload.estimated_amount_in_minor_units,
            currency=payload.currency.upper(),
            clinical_doc_refs=payload.clinical_documentation_reference_ids,
            diagnosis_codes=payload.diagnosis_codes,
            procedure_codes=payload.procedure_codes,
            notes=payload.notes,
        )

        PayerAuthorizationService.authorize_preauth_access(caller, record, action="create")
        created = self.auth_repo.create(record)

        logger.info(
            f"Created pre-authorization draft: id={created.id}, number={created.authorization_number}, "
            f"patient={created.patient_id}, service={created.service_code}"
        )
        return created.to_response()

    async def submit_preauthorization(
        self,
        caller: AuthenticatedUserContext,
        auth_id: str,
        payload: Optional[PreAuthorizationSubmitRequest] = None,
    ) -> PreAuthorizationResponse:
        """Submit pre-authorization request to payer gateway."""
        self._ensure_enabled()

        record = self.auth_repo.get(auth_id)
        if not record:
            raise AuthorizationNotFoundException(f"Pre-authorization {auth_id} not found.")

        PayerAuthorizationService.authorize_preauth_access(caller, record, action="submit")

        # Validate transition from current to SUBMITTED
        InsuranceValidationService.validate_auth_transition(record.status, PreAuthorizationStatus.SUBMITTED)
        record.status = PreAuthorizationStatus.SUBMITTED

        if payload and payload.notes:
            record.notes = f"{record.notes or ''}\nSubmission note: {payload.notes}".strip()
        if payload and payload.idempotency_key:
            record.idempotency_key = payload.idempotency_key

        try:
            prov_res = await self.provider.submit_authorization(record)
        except Exception as exc:
            logger.error(f"Payer gateway failed during authorization submission: {exc}")
            record.status = PreAuthorizationStatus.FAILED
            self.auth_repo.update(record)
            raise AuthorizationSubmissionFailedException(f"Authorization submission failed: {exc}")

        if prov_res.success:
            record.status = prov_res.status
            record.payer_reference = prov_res.payer_reference
            record.approved_amount_in_minor_units = prov_res.approved_amount_in_minor_units
            record.valid_from = prov_res.valid_from
            record.valid_to = prov_res.valid_to
            record.denial_reason = prov_res.denial_reason
            record.denial_code = prov_res.denial_code
            record.raw_response = prov_res.raw_response
        else:
            record.status = PreAuthorizationStatus.FAILED
            record.denial_reason = prov_res.error_message

        updated = self.auth_repo.update(record)
        logger.info(
            f"Pre-authorization submission processed: id={updated.id}, status={updated.status.value}, "
            f"ref={updated.payer_reference}"
        )
        return updated.to_response()

    def get_preauthorization(
        self,
        caller: AuthenticatedUserContext,
        auth_id: str,
    ) -> PreAuthorizationResponse:
        """Fetch pre-authorization record by ID."""
        self._ensure_enabled()
        record = self.auth_repo.get(auth_id)
        if not record:
            raise AuthorizationNotFoundException(f"Pre-authorization {auth_id} not found.")

        PayerAuthorizationService.authorize_preauth_access(caller, record, action="read")
        return record.to_response()

    async def sync_authorization_status(
        self,
        caller: AuthenticatedUserContext,
        auth_id: str,
    ) -> PreAuthorizationResponse:
        """Query live authorization status from payer."""
        self._ensure_enabled()
        record = self.auth_repo.get(auth_id)
        if not record:
            raise AuthorizationNotFoundException(f"Pre-authorization {auth_id} not found.")

        PayerAuthorizationService.authorize_preauth_access(caller, record, action="sync_status")

        if record.payer_reference:
            prov_res = await self.provider.get_authorization_status(record.payer_reference)
            if prov_res.success and prov_res.status != PreAuthorizationStatus.UNKNOWN:
                InsuranceValidationService.validate_auth_transition(record.status, prov_res.status)
                record.status = prov_res.status
                record.approved_amount_in_minor_units = prov_res.approved_amount_in_minor_units
                record.valid_from = prov_res.valid_from
                record.valid_to = prov_res.valid_to
                record.denial_reason = prov_res.denial_reason
                record.denial_code = prov_res.denial_code
                self.auth_repo.update(record)

        return record.to_response()

    def list_patient_preauthorizations(
        self,
        caller: AuthenticatedUserContext,
        patient_id: str,
        status: Optional[PreAuthorizationStatus] = None,
        limit: int = 50,
        offset: int = 0,
    ) -> Tuple[List[PreAuthorizationResponse], int]:
        """List prior authorizations filed for a patient."""
        self._ensure_enabled()
        records, total = self.auth_repo.list_by_patient(patient_id, status=status, limit=limit, offset=offset)
        return [r.to_response() for r in records], total
