"""Pydantic schemas for audit events.

Audit events are separate from application logs.
They record security/access decisions and consent lifecycle events.

CRITICAL — Audit events must NEVER contain:
- Clinical record content
- Diagnosis, symptoms, prescriptions
- Medication lists or medical history
- Passwords, tokens, or secrets
- PHI beyond minimum subject/actor identifiers
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, ConfigDict, Field


class AuditEventType(str, Enum):
    """Supported audit event type identifiers."""

    # Authorization events
    AUTHZ_ACCESS_GRANTED = "AUTHZ_ACCESS_GRANTED"
    AUTHZ_ACCESS_DENIED = "AUTHZ_ACCESS_DENIED"
    AUTHZ_PERMISSION_MISSING = "AUTHZ_PERMISSION_MISSING"
    AUTHZ_OWNERSHIP_FAILED = "AUTHZ_OWNERSHIP_FAILED"
    AUTHZ_RELATIONSHIP_FAILED = "AUTHZ_RELATIONSHIP_FAILED"

    # Consent lifecycle events
    CONSENT_CREATED = "CONSENT_CREATED"
    CONSENT_READ = "CONSENT_READ"
    CONSENT_REVOKED = "CONSENT_REVOKED"
    CONSENT_CHECK_PASSED = "CONSENT_CHECK_PASSED"
    CONSENT_CHECK_FAILED = "CONSENT_CHECK_FAILED"

    # Authentication events (mirrors Phase 2 logging for completeness)
    AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
    AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE"
    AUTH_REFRESH_SUCCESS = "AUTH_REFRESH_SUCCESS"
    AUTH_LOGOUT = "AUTH_LOGOUT"

    # Clinical record events (Phase 4)
    CLINICAL_RECORD_VIEWED = "CLINICAL_RECORD_VIEWED"
    PATIENT_PROFILE_UPDATED = "PATIENT_PROFILE_UPDATED"
    CLINICAL_HISTORY_CREATED = "CLINICAL_HISTORY_CREATED"
    CLINICAL_HISTORY_UPDATED = "CLINICAL_HISTORY_UPDATED"
    ALLERGY_CREATED = "ALLERGY_CREATED"
    ALLERGY_UPDATED = "ALLERGY_UPDATED"
    VITAL_RECORDED = "VITAL_RECORDED"
    ENCOUNTER_VIEWED = "ENCOUNTER_VIEWED"
    ENCOUNTER_CREATED = "ENCOUNTER_CREATED"
    CLINICAL_SUMMARY_VIEWED = "CLINICAL_SUMMARY_VIEWED"

    # Medical document events (Phase 5)
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_VIEWED = "DOCUMENT_VIEWED"
    DOCUMENT_DOWNLOAD_REQUESTED = "DOCUMENT_DOWNLOAD_REQUESTED"
    DOCUMENT_ARCHIVED = "DOCUMENT_ARCHIVED"
    DOCUMENT_PROCESSING_STARTED = "DOCUMENT_PROCESSING_STARTED"
    DOCUMENT_PROCESSING_COMPLETED = "DOCUMENT_PROCESSING_COMPLETED"
    DOCUMENT_PROCESSING_FAILED = "DOCUMENT_PROCESSING_FAILED"
    DOCUMENT_PROCESSING_RETRIED = "DOCUMENT_PROCESSING_RETRIED"
    DOCUMENT_EXTRACTION_CREATED = "DOCUMENT_EXTRACTION_CREATED"
    DOCUMENT_EXTRACTION_VIEWED = "DOCUMENT_EXTRACTION_VIEWED"

    # Prescription & Medication events (Phase 6)
    PRESCRIPTION_CREATED = "PRESCRIPTION_CREATED"
    PRESCRIPTION_VIEWED = "PRESCRIPTION_VIEWED"
    PRESCRIPTION_UPDATED = "PRESCRIPTION_UPDATED"
    PRESCRIPTION_NORMALIZATION_STARTED = "PRESCRIPTION_NORMALIZATION_STARTED"
    PRESCRIPTION_NORMALIZATION_COMPLETED = "PRESCRIPTION_NORMALIZATION_COMPLETED"
    PRESCRIPTION_NORMALIZATION_FAILED = "PRESCRIPTION_NORMALIZATION_FAILED"
    MEDICATION_CREATED = "MEDICATION_CREATED"
    MEDICATION_VIEWED = "MEDICATION_VIEWED"
    MEDICATION_UPDATED = "MEDICATION_UPDATED"
    MEDICATION_STATUS_CHANGED = "MEDICATION_STATUS_CHANGED"
    MEDICATION_CORRECTED = "MEDICATION_CORRECTED"

    # Medication Safety events (Phase 7)
    MEDICATION_SAFETY_CHECK_STARTED = "MEDICATION_SAFETY_CHECK_STARTED"
    MEDICATION_SAFETY_CHECK_COMPLETED = "MEDICATION_SAFETY_CHECK_COMPLETED"
    MEDICATION_SAFETY_CHECK_FAILED = "MEDICATION_SAFETY_CHECK_FAILED"
    MEDICATION_SAFETY_RESULT_VIEWED = "MEDICATION_SAFETY_RESULT_VIEWED"

    # Triage & SBAR events (Phase 8)
    SYMPTOM_INTAKE_CREATED = "SYMPTOM_INTAKE_CREATED"
    SYMPTOM_INTAKE_VIEWED = "SYMPTOM_INTAKE_VIEWED"
    TRIAGE_ASSESSMENT_STARTED = "TRIAGE_ASSESSMENT_STARTED"
    TRIAGE_ASSESSMENT_COMPLETED = "TRIAGE_ASSESSMENT_COMPLETED"
    TRIAGE_ASSESSMENT_FAILED = "TRIAGE_ASSESSMENT_FAILED"
    TRIAGE_REASSESSMENT_CREATED = "TRIAGE_REASSESSMENT_CREATED"
    SBAR_CREATED = "SBAR_CREATED"
    SBAR_VIEWED = "SBAR_VIEWED"
    SBAR_REGENERATED = "SBAR_REGENERATED"

    # Care Plan & Discharge events (Phase 9)
    DISCHARGE_EXTRACTION_STARTED = "DISCHARGE_EXTRACTION_STARTED"
    DISCHARGE_EXTRACTION_COMPLETED = "DISCHARGE_EXTRACTION_COMPLETED"
    DISCHARGE_EXTRACTION_FAILED = "DISCHARGE_EXTRACTION_FAILED"
    DISCHARGE_VERIFIED = "DISCHARGE_VERIFIED"
    CARE_PLAN_CREATED = "CARE_PLAN_CREATED"
    CARE_PLAN_UPDATED = "CARE_PLAN_UPDATED"
    CARE_PLAN_VIEWED = "CARE_PLAN_VIEWED"
    CARE_PLAN_STATUS_CHANGED = "CARE_PLAN_STATUS_CHANGED"

    # Doctor Clinical Workflow events (Phase 10)
    CLINICAL_NOTE_CREATED = "CLINICAL_NOTE_CREATED"
    CLINICAL_NOTE_UPDATED = "CLINICAL_NOTE_UPDATED"
    CLINICAL_NOTE_SIGNED = "CLINICAL_NOTE_SIGNED"
    CLINICAL_NOTE_VIEWED = "CLINICAL_NOTE_VIEWED"
    CLINICAL_ASSESSMENT_CREATED = "CLINICAL_ASSESSMENT_CREATED"
    CLINICAL_ASSESSMENT_UPDATED = "CLINICAL_ASSESSMENT_UPDATED"
    CLINICAL_ASSESSMENT_FINALIZED = "CLINICAL_ASSESSMENT_FINALIZED"
    CLINICAL_ASSESSMENT_VIEWED = "CLINICAL_ASSESSMENT_VIEWED"
    CLINICAL_PLAN_CREATED = "CLINICAL_PLAN_CREATED"
    CLINICAL_PLAN_UPDATED = "CLINICAL_PLAN_UPDATED"
    CLINICAL_PLAN_FINALIZED = "CLINICAL_PLAN_FINALIZED"
    CLINICAL_PLAN_VIEWED = "CLINICAL_PLAN_VIEWED"
    CLINICAL_WORKSPACE_ACCESSED = "CLINICAL_WORKSPACE_ACCESSED"

    # Hospital & Organization Network events (Phase 11)
    ORGANIZATION_LIST_VIEWED = "ORGANIZATION_LIST_VIEWED"
    ORGANIZATION_VIEWED = "ORGANIZATION_VIEWED"
    FACILITY_LIST_VIEWED = "FACILITY_LIST_VIEWED"
    FACILITY_VIEWED = "FACILITY_VIEWED"
    DEPARTMENT_LIST_VIEWED = "DEPARTMENT_LIST_VIEWED"
    CLINICIAN_ORGANIZATIONS_VIEWED = "CLINICIAN_ORGANIZATIONS_VIEWED"
    CLINICIAN_FACILITIES_VIEWED = "CLINICIAN_FACILITIES_VIEWED"
    ORGANIZATION_CONTEXT_VIEWED = "ORGANIZATION_CONTEXT_VIEWED"
    FACILITY_CONTEXT_VIEWED = "FACILITY_CONTEXT_VIEWED"

    # Facility Discovery & Transfer events (Phase 12)
    FACILITY_DISCOVERY_STARTED = "FACILITY_DISCOVERY_STARTED"
    FACILITY_DISCOVERY_COMPLETED = "FACILITY_DISCOVERY_COMPLETED"
    FACILITY_DISCOVERY_FAILED = "FACILITY_DISCOVERY_FAILED"
    FACILITY_VIEWED_FOR_TRANSFER = "FACILITY_VIEWED_FOR_TRANSFER"
    TRANSFER_CREATED = "TRANSFER_CREATED"
    TRANSFER_VIEWED = "TRANSFER_VIEWED"
    TRANSFER_STATUS_UPDATED = "TRANSFER_STATUS_UPDATED"
    TRANSFER_ACCEPTED = "TRANSFER_ACCEPTED"
    TRANSFER_DECLINED = "TRANSFER_DECLINED"
    TRANSFER_CANCELLED = "TRANSFER_CANCELLED"
    TRANSFER_COMPLETED = "TRANSFER_COMPLETED"
    TRANSFER_FAILED = "TRANSFER_FAILED"
    TRANSFER_CLINICAL_CONTEXT_SHARED = "TRANSFER_CLINICAL_CONTEXT_SHARED"
    TRANSFER_SBAR_ATTACHED = "TRANSFER_SBAR_ATTACHED"

    # Interoperability & Healthcare Data Exchange events (Phase 13)
    INTEROPERABILITY_IMPORT_STARTED = "INTEROPERABILITY_IMPORT_STARTED"
    INTEROPERABILITY_IMPORT_COMPLETED = "INTEROPERABILITY_IMPORT_COMPLETED"
    INTEROPERABILITY_IMPORT_FAILED = "INTEROPERABILITY_IMPORT_FAILED"
    INTEROPERABILITY_IMPORT_REJECTED = "INTEROPERABILITY_IMPORT_REJECTED"
    INTEROPERABILITY_EXPORT_STARTED = "INTEROPERABILITY_EXPORT_STARTED"
    INTEROPERABILITY_EXPORT_COMPLETED = "INTEROPERABILITY_EXPORT_COMPLETED"
    INTEROPERABILITY_EXPORT_FAILED = "INTEROPERABILITY_EXPORT_FAILED"
    INTEROPERABILITY_RESOURCE_VIEWED = "INTEROPERABILITY_RESOURCE_VIEWED"
    EXTERNAL_IDENTITY_RESOLVED = "EXTERNAL_IDENTITY_RESOLVED"
    EXTERNAL_IDENTITY_UNRESOLVED = "EXTERNAL_IDENTITY_UNRESOLVED"
    INTEROPERABILITY_DATA_SHARED = "INTEROPERABILITY_DATA_SHARED"
    INTEROPERABILITY_VERIFICATION_REQUIRED = "INTEROPERABILITY_VERIFICATION_REQUIRED"

    # AI & Intelligence Layer events (Phase 14)
    AI_TASK_CREATED = "AI_TASK_CREATED"
    AI_TASK_STARTED = "AI_TASK_STARTED"
    AI_TASK_COMPLETED = "AI_TASK_COMPLETED"
    AI_TASK_FAILED = "AI_TASK_FAILED"
    AI_TASK_RETRIED = "AI_TASK_RETRIED"
    AI_OUTPUT_VALIDATION_FAILED = "AI_OUTPUT_VALIDATION_FAILED"
    AI_GROUNDING_VALIDATION_FAILED = "AI_GROUNDING_VALIDATION_FAILED"
    AI_RESULT_VIEWED = "AI_RESULT_VIEWED"
    AI_RESULT_REGENERATED = "AI_RESULT_REGENERATED"
    AI_RESULT_REVIEW_REQUIRED = "AI_RESULT_REVIEW_REQUIRED"
    AI_RESULT_VERIFIED = "AI_RESULT_VERIFIED"
    AI_RESULT_CORRECTED = "AI_RESULT_CORRECTED"
    AI_RESULT_REJECTED = "AI_RESULT_REJECTED"
    AI_PROVIDER_ERROR = "AI_PROVIDER_ERROR"
    AI_PROVIDER_TIMEOUT = "AI_PROVIDER_TIMEOUT"
    AI_PROMPT_VERSION_USED = "AI_PROMPT_VERSION_USED"

    # Asynchronous Workflow & Event-Driven execution events (Phase 22)
    JOB_CREATED = "JOB_CREATED"
    JOB_QUEUED = "JOB_QUEUED"
    JOB_STARTED = "JOB_STARTED"
    JOB_COMPLETED = "JOB_COMPLETED"
    JOB_FAILED = "JOB_FAILED"
    JOB_RETRY_SCHEDULED = "JOB_RETRY_SCHEDULED"
    JOB_CANCELLED = "JOB_CANCELLED"
    EVENT_PUBLISHED = "EVENT_PUBLISHED"
    EVENT_CONSUMED = "EVENT_CONSUMED"
    EVENT_DUPLICATE_IGNORED = "EVENT_DUPLICATE_IGNORED"
    WORKFLOW_STARTED = "WORKFLOW_STARTED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
    WORKFLOW_FAILED = "WORKFLOW_FAILED"

    # Advanced Data Privacy, Lifecycle & Governance events (Phase 24)
    PRIVACY_POLICY_CHECKED = "PRIVACY_POLICY_CHECKED"
    SENSITIVE_DATA_ACCESSED = "SENSITIVE_DATA_ACCESSED"
    DATA_EXPORT_REQUESTED = "DATA_EXPORT_REQUESTED"
    DATA_EXPORT_COMPLETED = "DATA_EXPORT_COMPLETED"
    DATA_EXPORT_FAILED = "DATA_EXPORT_FAILED"
    DATA_EXPORT_DOWNLOADED = "DATA_EXPORT_DOWNLOADED"
    DATA_EXPORT_EXPIRED = "DATA_EXPORT_EXPIRED"
    RETENTION_EVALUATED = "RETENTION_EVALUATED"
    RESOURCE_ARCHIVE_STARTED = "RESOURCE_ARCHIVE_STARTED"
    RESOURCE_ARCHIVED = "RESOURCE_ARCHIVED"
    RESOURCE_DELETION_REQUESTED = "RESOURCE_DELETION_REQUESTED"
    RESOURCE_DELETION_COMPLETED = "RESOURCE_DELETION_COMPLETED"
    RESOURCE_DELETION_FAILED = "RESOURCE_DELETION_FAILED"
    DEIDENTIFICATION_STARTED = "DEIDENTIFICATION_STARTED"
    DEIDENTIFICATION_COMPLETED = "DEIDENTIFICATION_COMPLETED"
    PSEUDONYMIZATION_COMPLETED = "PSEUDONYMIZATION_COMPLETED"
    PRIVACY_POLICY_DENIED = "PRIVACY_POLICY_DENIED"

    # Feature Flags, Configuration Governance & Controlled Rollout (Phase 25)
    CONFIGURATION_CREATED = "CONFIGURATION_CREATED"
    CONFIGURATION_UPDATED = "CONFIGURATION_UPDATED"
    CONFIGURATION_DELETED = "CONFIGURATION_DELETED"
    FEATURE_FLAG_ENABLED = "FEATURE_FLAG_ENABLED"
    FEATURE_FLAG_DISABLED = "FEATURE_FLAG_DISABLED"
    FEATURE_FLAG_ROLLOUT_CHANGED = "FEATURE_FLAG_ROLLOUT_CHANGED"
    PROVIDER_CONFIGURATION_CHANGED = "PROVIDER_CONFIGURATION_CHANGED"
    KILL_SWITCH_ENABLED = "KILL_SWITCH_ENABLED"
    KILL_SWITCH_DISABLED = "KILL_SWITCH_DISABLED"
    CONFIGURATION_VALIDATION_FAILED = "CONFIGURATION_VALIDATION_FAILED"

    # Data Quality, Clinical Record Integrity & Reconciliation events (Phase 26)
    DATA_QUALITY_CHECK_STARTED = "DATA_QUALITY_CHECK_STARTED"
    DATA_QUALITY_CHECK_COMPLETED = "DATA_QUALITY_CHECK_COMPLETED"
    DATA_QUALITY_CHECK_FAILED = "DATA_QUALITY_CHECK_FAILED"
    DATA_QUALITY_FINDING_CREATED = "DATA_QUALITY_FINDING_CREATED"
    DATA_QUALITY_FINDING_VIEWED = "DATA_QUALITY_FINDING_VIEWED"
    DATA_QUALITY_REVIEW_STARTED = "DATA_QUALITY_REVIEW_STARTED"
    DATA_QUALITY_FINDING_RESOLVED = "DATA_QUALITY_FINDING_RESOLVED"
    DATA_QUALITY_FINDING_REJECTED = "DATA_QUALITY_FINDING_REJECTED"
    DUPLICATE_DETECTED = "DUPLICATE_DETECTED"
    DUPLICATE_CONFIRMED = "DUPLICATE_CONFIRMED"
    DUPLICATE_REJECTED = "DUPLICATE_REJECTED"
    RECONCILIATION_STARTED = "RECONCILIATION_STARTED"
    RECONCILIATION_COMPLETED = "RECONCILIATION_COMPLETED"
    RECONCILIATION_FAILED = "RECONCILIATION_FAILED"
    RECONCILIATION_RESOLVED = "RECONCILIATION_RESOLVE"
    CLINICAL_RECORD_CORRECTED = "CLINICAL_RECORD_CORRECTED"
    CLINICAL_RECORD_SUPERSEDED = "CLINICAL_RECORD_SUPERSEDED"
    EXTERNAL_DATA_CONFLICT_DETECTED = "EXTERNAL_DATA_CONFLICT_DETECTED"

    # Administration, Support Operations & Controlled Backoffice (Phase 27)
    ADMIN_SYSTEM_STATUS_VIEWED = "ADMIN_SYSTEM_STATUS_VIEWED"
    ADMIN_JOB_VIEWED = "ADMIN_JOB_VIEWED"
    ADMIN_JOB_RETRIED = "ADMIN_JOB_RETRIED"
    ADMIN_JOB_CANCELLED = "ADMIN_JOB_CANCELLED"
    ADMIN_INTEGRATION_VIEWED = "ADMIN_INTEGRATION_VIEWED"
    ADMIN_INTEGRATION_TESTED = "ADMIN_INTEGRATION_TESTED"
    ADMIN_INCIDENT_CREATED = "ADMIN_INCIDENT_CREATED"
    ADMIN_INCIDENT_UPDATED = "ADMIN_INCIDENT_UPDATED"
    ADMIN_INCIDENT_RESOLVED = "ADMIN_INCIDENT_RESOLVED"
    ADMIN_AUDIT_VIEWED = "ADMIN_AUDIT_VIEWED"
    ADMIN_SECURITY_EVENT_VIEWED = "ADMIN_SECURITY_EVENT_VIEWED"
    ADMIN_DATA_QUALITY_VIEWED = "ADMIN_DATA_QUALITY_VIEWED"
    ADMIN_SUPPORT_LOOKUP = "ADMIN_SUPPORT_LOOKUP"
    ADMIN_CONFIGURATION_VIEWED = "ADMIN_CONFIGURATION_VIEWED"
    ADMIN_CONFIGURATION_CHANGED = "ADMIN_CONFIGURATION_CHANGED"

    # Notification, Communication & Event Delivery System (Phase 29)
    NOTIFICATION_CREATED = "NOTIFICATION_CREATED"
    NOTIFICATION_QUEUED = "NOTIFICATION_QUEUED"
    NOTIFICATION_SENT = "NOTIFICATION_SENT"
    NOTIFICATION_DELIVERED = "NOTIFICATION_DELIVERED"
    NOTIFICATION_FAILED = "NOTIFICATION_FAILED"
    NOTIFICATION_RETRY_STARTED = "NOTIFICATION_RETRY_STARTED"
    NOTIFICATION_CANCELLED = "NOTIFICATION_CANCELLED"
    NOTIFICATION_READ = "NOTIFICATION_READ"
    NOTIFICATION_DISMISSED = "NOTIFICATION_DISMISSED"
    NOTIFICATION_PREFERENCE_CHANGED = "NOTIFICATION_PREFERENCE_CHANGED"
    NOTIFICATION_PROVIDER_TESTED = "NOTIFICATION_PROVIDER_TESTED"
    NOTIFICATION_BULK_OPERATION_STARTED = "NOTIFICATION_BULK_OPERATION_STARTED"
    NOTIFICATION_BULK_OPERATION_COMPLETED = "NOTIFICATION_BULK_OPERATION_COMPLETED"

    # Authorized Search, Indexing & Clinical Resource Retrieval (Phase 30)
    SEARCH_EXECUTED = "SEARCH_EXECUTED"
    PATIENT_SEARCH_EXECUTED = "PATIENT_SEARCH_EXECUTED"
    CLINICAL_RESOURCE_SEARCH_EXECUTED = "CLINICAL_RESOURCE_SEARCH_EXECUTED"
    DOCUMENT_SEARCH_EXECUTED = "DOCUMENT_SEARCH_EXECUTED"
    CLINICAL_NOTE_SEARCH_EXECUTED = "CLINICAL_NOTE_SEARCH_EXECUTED"
    MEDICATION_SEARCH_EXECUTED = "MEDICATION_SEARCH_EXECUTED"
    FACILITY_SEARCH_EXECUTED = "FACILITY_SEARCH_EXECUTED"
    ORGANIZATION_SEARCH_EXECUTED = "ORGANIZATION_SEARCH_EXECUTED"
    SEARCH_RESULT_VIEWED = "SEARCH_RESULT_VIEWED"
    SEARCH_PROVIDER_FAILED = "SEARCH_PROVIDER_FAILED"
    SEARCH_INDEX_UPDATE_STARTED = "SEARCH_INDEX_UPDATE_STARTED"
    SEARCH_INDEX_UPDATE_COMPLETED = "SEARCH_INDEX_UPDATE_COMPLETED"
    SEARCH_INDEX_UPDATE_FAILED = "SEARCH_INDEX_UPDATE_FAILED"
    SEARCH_INDEX_REBUILT = "SEARCH_INDEX_REBUILT"

    # Scheduling, Appointment & Clinical Access Management (Phase 31)
    APPOINTMENT_CREATED = "APPOINTMENT_CREATED"
    APPOINTMENT_VIEWED = "APPOINTMENT_VIEWED"
    APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED"
    APPOINTMENT_RESCHEDULE_STARTED = "APPOINTMENT_RESCHEDULE_STARTED"
    APPOINTMENT_RESCHEDULED = "APPOINTMENT_RESCHEDULED"
    APPOINTMENT_CANCEL_REQUESTED = "APPOINTMENT_CANCEL_REQUESTED"
    APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED"
    APPOINTMENT_STATUS_UPDATED = "APPOINTMENT_STATUS_UPDATED"
    APPOINTMENT_CHECKED_IN = "APPOINTMENT_CHECKED_IN"
    APPOINTMENT_COMPLETED = "APPOINTMENT_COMPLETED"
    APPOINTMENT_NO_SHOW = "APPOINTMENT_NO_SHOW"
    AVAILABILITY_VIEWED = "AVAILABILITY_VIEWED"
    AVAILABILITY_SEARCH_EXECUTED = "AVAILABILITY_SEARCH_EXECUTED"
    SCHEDULE_VIEWED = "SCHEDULE_VIEWED"
    SCHEDULE_UPDATED = "SCHEDULE_UPDATED"
    BOOKING_CONFLICT_DETECTED = "BOOKING_CONFLICT_DETECTED"
    BOOKING_PROVIDER_FAILED = "BOOKING_PROVIDER_FAILED"
    BOOKING_PROVIDER_TIMEOUT = "BOOKING_PROVIDER_TIMEOUT"
    BOOKING_RECONCILIATION_STARTED = "BOOKING_RECONCILIATION_STARTED"
    BOOKING_RECONCILIATION_COMPLETED = "BOOKING_RECONCILIATION_COMPLETED"
    APPOINTMENT_REMINDER_SCHEDULED = "APPOINTMENT_REMINDER_SCHEDULED"

    # Billing, Payments & Financial Transaction Management (Phase 32)
    INVOICE_CREATED = "INVOICE_CREATED"
    INVOICE_VIEWED = "INVOICE_VIEWED"
    INVOICE_ISSUED = "INVOICE_ISSUED"
    INVOICE_CANCELLED = "INVOICE_CANCELLED"
    INVOICE_PAID = "INVOICE_PAID"
    INVOICE_REFUNDED = "INVOICE_REFUNDED"
    PAYMENT_CREATED = "PAYMENT_CREATED"
    PAYMENT_PROCESSING = "PAYMENT_PROCESSING"
    PAYMENT_SUCCEEDED = "PAYMENT_SUCCEEDED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYMENT_UNKNOWN = "PAYMENT_UNKNOWN"
    PAYMENT_RECONCILIATION_STARTED = "PAYMENT_RECONCILIATION_STARTED"
    PAYMENT_RECONCILIATION_COMPLETED = "PAYMENT_RECONCILIATION_COMPLETED"
    PAYMENT_RECONCILIATION_FAILED = "PAYMENT_RECONCILIATION_FAILED"
    REFUND_CREATED = "REFUND_CREATED"
    REFUND_PROCESSING = "REFUND_PROCESSING"
    REFUND_SUCCEEDED = "REFUND_SUCCEEDED"
    REFUND_FAILED = "REFUND_FAILED"
    PAYMENT_WEBHOOK_RECEIVED = "PAYMENT_WEBHOOK_RECEIVED"
    PAYMENT_WEBHOOK_REJECTED = "PAYMENT_WEBHOOK_REJECTED"
    PAYMENT_WEBHOOK_DUPLICATE = "PAYMENT_WEBHOOK_DUPLICATE"
    BILLING_ACCESS_DENIED = "BILLING_ACCESS_DENIED"
    BILLING_PROVIDER_TESTED = "BILLING_PROVIDER_TESTED"
    BILLING_CONFIGURATION_CHANGED = "BILLING_CONFIGURATION_CHANGED"

    # Insurance, Claims & Payer Integration (Phase 33)
    INSURANCE_CREATED = "INSURANCE_CREATED"
    INSURANCE_VIEWED = "INSURANCE_VIEWED"
    INSURANCE_UPDATED = "INSURANCE_UPDATED"
    INSURANCE_VERIFIED = "INSURANCE_VERIFIED"
    INSURANCE_CORRECTED = "INSURANCE_CORRECTED"
    ELIGIBILITY_CHECK_STARTED = "ELIGIBILITY_CHECK_STARTED"
    ELIGIBILITY_CHECK_COMPLETED = "ELIGIBILITY_CHECK_COMPLETED"
    ELIGIBILITY_CHECK_FAILED = "ELIGIBILITY_CHECK_FAILED"
    ELIGIBILITY_CHECK_UNKNOWN = "ELIGIBILITY_CHECK_UNKNOWN"
    BENEFIT_CHECK_STARTED = "BENEFIT_CHECK_STARTED"
    BENEFIT_CHECK_COMPLETED = "BENEFIT_CHECK_COMPLETED"
    BENEFIT_CHECK_FAILED = "BENEFIT_CHECK_FAILED"
    AUTHORIZATION_CREATED = "AUTHORIZATION_CREATED"
    AUTHORIZATION_SUBMITTED = "AUTHORIZATION_SUBMITTED"
    AUTHORIZATION_APPROVED = "AUTHORIZATION_APPROVED"
    AUTHORIZATION_DENIED = "AUTHORIZATION_DENIED"
    AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED"
    AUTHORIZATION_VIEWED = "AUTHORIZATION_VIEWED"
    CLAIM_CREATED = "CLAIM_CREATED"
    CLAIM_VIEWED = "CLAIM_VIEWED"
    CLAIM_VALIDATED = "CLAIM_VALIDATED"
    CLAIM_VALIDATION_FAILED = "CLAIM_VALIDATION_FAILED"
    CLAIM_SUBMITTED = "CLAIM_SUBMITTED"
    CLAIM_RECEIVED = "CLAIM_RECEIVED"
    CLAIM_APPROVED = "CLAIM_APPROVED"
    CLAIM_DENIED = "CLAIM_DENIED"
    CLAIM_REJECTED = "CLAIM_REJECTED"
    CLAIM_RECONCILIATION_STARTED = "CLAIM_RECONCILIATION_STARTED"
    CLAIM_RECONCILIATION_COMPLETED = "CLAIM_RECONCILIATION_COMPLETED"
    CLAIM_RECONCILIATION_FAILED = "CLAIM_RECONCILIATION_FAILED"
    PAYER_WEBHOOK_RECEIVED = "PAYER_WEBHOOK_RECEIVED"
    PAYER_WEBHOOK_REJECTED = "PAYER_WEBHOOK_REJECTED"
    PAYER_WEBHOOK_DUPLICATE = "PAYER_WEBHOOK_DUPLICATE"
    PAYER_PROVIDER_TESTED = "PAYER_PROVIDER_TESTED"
    INSURANCE_ACCESS_DENIED = "INSURANCE_ACCESS_DENIED"
    CLAIM_ACCESS_DENIED = "CLAIM_ACCESS_DENIED"
    AUTHORIZATION_ACCESS_DENIED = "AUTHORIZATION_ACCESS_DENIED"

    # Phase 34: Laboratory & Diagnostics Audit Events
    DIAGNOSTIC_TEST_VIEWED = "DIAGNOSTIC_TEST_VIEWED"
    DIAGNOSTIC_ORDER_CREATED = "DIAGNOSTIC_ORDER_CREATED"
    DIAGNOSTIC_ORDER_VIEWED = "DIAGNOSTIC_ORDER_VIEWED"
    DIAGNOSTIC_ORDER_SUBMITTED = "DIAGNOSTIC_ORDER_SUBMITTED"
    DIAGNOSTIC_ORDER_ACCEPTED = "DIAGNOSTIC_ORDER_ACCEPTED"
    DIAGNOSTIC_ORDER_CANCELLED = "DIAGNOSTIC_ORDER_CANCELLED"
    DIAGNOSTIC_ORDER_FAILED = "DIAGNOSTIC_ORDER_FAILED"

    SPECIMEN_CREATED = "SPECIMEN_CREATED"
    SPECIMEN_COLLECTED = "SPECIMEN_COLLECTED"
    SPECIMEN_RECEIVED = "SPECIMEN_RECEIVED"
    SPECIMEN_REJECTED = "SPECIMEN_REJECTED"

    DIAGNOSTIC_RESULT_RECEIVED = "DIAGNOSTIC_RESULT_RECEIVED"
    DIAGNOSTIC_RESULT_VIEWED = "DIAGNOSTIC_RESULT_VIEWED"
    DIAGNOSTIC_RESULT_NORMALIZED = "DIAGNOSTIC_RESULT_NORMALIZED"
    DIAGNOSTIC_RESULT_VERIFICATION_STARTED = "DIAGNOSTIC_RESULT_VERIFICATION_STARTED"
    DIAGNOSTIC_RESULT_VERIFIED = "DIAGNOSTIC_RESULT_VERIFIED"
    DIAGNOSTIC_RESULT_CORRECTED = "DIAGNOSTIC_RESULT_CORRECTED"
    DIAGNOSTIC_RESULT_REJECTED = "DIAGNOSTIC_RESULT_REJECTED"
    DIAGNOSTIC_RESULT_SUPERSEDED = "DIAGNOSTIC_RESULT_SUPERSEDED"

    DIAGNOSTIC_REPORT_RECEIVED = "DIAGNOSTIC_REPORT_RECEIVED"
    DIAGNOSTIC_REPORT_VIEWED = "DIAGNOSTIC_REPORT_VIEWED"

    CRITICAL_RESULT_REVIEW_REQUIRED = "CRITICAL_RESULT_REVIEW_REQUIRED"
    CRITICAL_RESULT_NOTIFICATION_CREATED = "CRITICAL_RESULT_NOTIFICATION_CREATED"

    DIAGNOSTIC_RECONCILIATION_STARTED = "DIAGNOSTIC_RECONCILIATION_STARTED"
    DIAGNOSTIC_RECONCILIATION_COMPLETED = "DIAGNOSTIC_RECONCILIATION_COMPLETED"
    DIAGNOSTIC_RECONCILIATION_FAILED = "DIAGNOSTIC_RECONCILIATION_FAILED"

    DIAGNOSTIC_PROVIDER_TESTED = "DIAGNOSTIC_PROVIDER_TESTED"
    DIAGNOSTIC_WEBHOOK_RECEIVED = "DIAGNOSTIC_WEBHOOK_RECEIVED"
    DIAGNOSTIC_WEBHOOK_REJECTED = "DIAGNOSTIC_WEBHOOK_REJECTED"
    DIAGNOSTIC_WEBHOOK_DUPLICATE = "DIAGNOSTIC_WEBHOOK_DUPLICATE"

    DIAGNOSTIC_ACCESS_DENIED = "DIAGNOSTIC_ACCESS_DENIED"

    # Phase 35: Clinical Alerts, Safety Notifications & Escalation Management
    ALERT_CREATED = "ALERT_CREATED"
    ALERT_VIEWED = "ALERT_VIEWED"
    ALERT_DELIVERY_REQUESTED = "ALERT_DELIVERY_REQUESTED"
    ALERT_DELIVERED = "ALERT_DELIVERED"
    ALERT_DELIVERY_FAILED = "ALERT_DELIVERY_FAILED"
    ALERT_ACKNOWLEDGED = "ALERT_ACKNOWLEDGED"
    ALERT_ESCALATION_SCHEDULED = "ALERT_ESCALATION_SCHEDULED"
    ALERT_ESCALATED = "ALERT_ESCALATED"
    ALERT_RESOLVED = "ALERT_RESOLVED"
    ALERT_DISMISSED = "ALERT_DISMISSED"
    ALERT_EXPIRED = "ALERT_EXPIRED"
    ALERT_POLICY_EVALUATED = "ALERT_POLICY_EVALUATED"
    ALERT_SUPPRESSED = "ALERT_SUPPRESSED"
    ALERT_RECIPIENT_RESOLVED = "ALERT_RECIPIENT_RESOLVED"
    ALERT_ACCESS_DENIED = "ALERT_ACCESS_DENIED"

    # Phase 36: Clinical Tasks, Work Queues & Action Management
    TASK_CREATED = "TASK_CREATED"
    TASK_VIEWED = "TASK_VIEWED"
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_REASSIGNED = "TASK_REASSIGNED"
    TASK_ACCEPTED = "TASK_ACCEPTED"
    TASK_STARTED = "TASK_STARTED"
    TASK_BLOCKED = "TASK_BLOCKED"
    TASK_UNBLOCKED = "TASK_UNBLOCKED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_VERIFICATION_REQUESTED = "TASK_VERIFICATION_REQUESTED"
    TASK_VERIFIED = "TASK_VERIFIED"
    TASK_REJECTED = "TASK_REJECTED"
    TASK_CANCELLED = "TASK_CANCELLED"
    TASK_EXPIRED = "TASK_EXPIRED"
    TASK_FAILED = "TASK_FAILED"
    TASK_ESCALATED = "TASK_ESCALATED"
    TASK_ACCESS_DENIED = "TASK_ACCESS_DENIED"

    # Phase 37: Clinical Workflow Orchestration, Order Management & Controlled Action Chains
    WORKFLOW_CREATED = "WORKFLOW_CREATED"
    WORKFLOW_VIEWED = "WORKFLOW_VIEWED"
    WORKFLOW_STEP_STARTED = "WORKFLOW_STEP_STARTED"
    WORKFLOW_STEP_COMPLETED = "WORKFLOW_STEP_COMPLETED"
    WORKFLOW_STEP_FAILED = "WORKFLOW_STEP_FAILED"
    WORKFLOW_STEP_RETRIED = "WORKFLOW_STEP_RETRIED"
    WORKFLOW_APPROVAL_REQUESTED = "WORKFLOW_APPROVAL_REQUESTED"
    WORKFLOW_APPROVED = "WORKFLOW_APPROVED"
    WORKFLOW_REJECTED = "WORKFLOW_REJECTED"
    WORKFLOW_PAUSED = "WORKFLOW_PAUSED"
    WORKFLOW_RESUMED = "WORKFLOW_RESUMED"
    WORKFLOW_BLOCKED = "WORKFLOW_BLOCKED"
    WORKFLOW_UNBLOCKED = "WORKFLOW_UNBLOCKED"
    WORKFLOW_CANCELLED = "WORKFLOW_CANCELLED"
    WORKFLOW_EXPIRED = "WORKFLOW_EXPIRED"
    WORKFLOW_ACCESS_DENIED = "WORKFLOW_ACCESS_DENIED"

    # Phase 38: Clinical Orders, Results & Controlled Action Execution Audit Events
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_VIEWED = "ORDER_VIEWED"
    ORDER_LISTED = "ORDER_LISTED"
    ORDER_AUTHORIZATION_REQUESTED = "ORDER_AUTHORIZATION_REQUESTED"
    ORDER_AUTHORIZED = "ORDER_AUTHORIZED"
    ORDER_REJECTED = "ORDER_REJECTED"
    ORDER_SUBMITTED = "ORDER_SUBMITTED"
    ORDER_TRANSMISSION_STARTED = "ORDER_TRANSMISSION_STARTED"
    ORDER_TRANSMISSION_SUCCEEDED = "ORDER_TRANSMISSION_SUCCEEDED"
    ORDER_TRANSMISSION_FAILED = "ORDER_TRANSMISSION_FAILED"
    ORDER_SUBMISSION_UNKNOWN = "ORDER_SUBMISSION_UNKNOWN"
    ORDER_ACCEPTED = "ORDER_ACCEPTED"
    ORDER_STATUS_UPDATED = "ORDER_STATUS_UPDATED"
    ORDER_CANCEL_REQUESTED = "ORDER_CANCEL_REQUESTED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    ORDER_REVISION_CREATED = "ORDER_REVISION_CREATED"
    ORDER_RESULT_LINKED = "ORDER_RESULT_LINKED"
    ORDER_RESULT_VIEWED = "ORDER_RESULT_VIEWED"
    ORDER_VERIFICATION_REQUESTED = "ORDER_VERIFICATION_REQUESTED"
    ORDER_VERIFIED = "ORDER_VERIFIED"
    ORDER_RECONCILIATION_STARTED = "ORDER_RECONCILIATION_STARTED"
    ORDER_RECONCILIATION_COMPLETED = "ORDER_RECONCILIATION_COMPLETED"
    ORDER_RECONCILIATION_REQUIRED = "ORDER_RECONCILIATION_REQUIRED"
    ORDER_FAILED = "ORDER_FAILED"
    ORDER_EXPIRED = "ORDER_EXPIRED"
    ORDER_PROVIDER_TESTED = "ORDER_PROVIDER_TESTED"
    ORDER_WEBHOOK_RECEIVED = "ORDER_WEBHOOK_RECEIVED"
    ORDER_WEBHOOK_REJECTED = "ORDER_WEBHOOK_REJECTED"
    ORDER_WEBHOOK_DUPLICATE = "ORDER_WEBHOOK_DUPLICATE"
    ORDER_ACCESS_DENIED = "ORDER_ACCESS_DENIED"
    ORDER_ADMIN_RETRY = "ORDER_ADMIN_RETRY"

    # Phase 39: Clinical Order Sets, Protocol Templates & Controlled Order Composition Audit Events
    ORDER_SET_TEMPLATE_CREATED = "ORDER_SET_TEMPLATE_CREATED"
    ORDER_SET_TEMPLATE_APPROVED = "ORDER_SET_TEMPLATE_APPROVED"
    ORDER_SET_TEMPLATE_ACTIVATED = "ORDER_SET_TEMPLATE_ACTIVATED"
    ORDER_SET_TEMPLATE_SUSPENDED = "ORDER_SET_TEMPLATE_SUSPENDED"
    ORDER_SET_TEMPLATE_DEPRECATED = "ORDER_SET_TEMPLATE_DEPRECATED"
    ORDER_SET_VERSION_CREATED = "ORDER_SET_VERSION_CREATED"
    ORDER_SET_VERSION_RESOLVED = "ORDER_SET_VERSION_RESOLVED"
    ORDER_SET_SELECTED = "ORDER_SET_SELECTED"
    ORDER_SET_PREVIEW_GENERATED = "ORDER_SET_PREVIEW_GENERATED"
    ORDER_SET_VALIDATION_STARTED = "ORDER_SET_VALIDATION_STARTED"
    ORDER_SET_VALIDATION_FAILED = "ORDER_SET_VALIDATION_FAILED"
    ORDER_SET_AUTHORIZATION_REQUESTED = "ORDER_SET_AUTHORIZATION_REQUESTED"
    ORDER_SET_AUTHORIZED = "ORDER_SET_AUTHORIZED"
    ORDER_SET_EXPANSION_STARTED = "ORDER_SET_EXPANSION_STARTED"
    ORDER_SET_EXPANSION_COMPLETED = "ORDER_SET_EXPANSION_COMPLETED"
    ORDER_SET_EXECUTION_STARTED = "ORDER_SET_EXECUTION_STARTED"
    ORDER_SET_PARTIAL_FAILURE = "ORDER_SET_PARTIAL_FAILURE"
    ORDER_SET_COMPLETED = "ORDER_SET_COMPLETED"
    ORDER_SET_FAILED = "ORDER_SET_FAILED"
    ORDER_SET_CANCELLED = "ORDER_SET_CANCELLED"
    ORDER_SET_RECONCILIATION_REQUIRED = "ORDER_SET_RECONCILIATION_REQUIRED"
    ORDER_SET_ACCESS_DENIED = "ORDER_SET_ACCESS_DENIED"

    # Phase 40: Clinical Order Review, Approval Gates & Controlled Authorization Management Audit Events
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_ASSIGNED = "APPROVAL_ASSIGNED"
    APPROVAL_STARTED = "APPROVAL_STARTED"
    APPROVAL_APPROVED = "APPROVAL_APPROVED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    APPROVAL_REVISION_REQUESTED = "APPROVAL_REVISION_REQUESTED"
    APPROVAL_CANCELLED = "APPROVAL_CANCELLED"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    APPROVAL_ESCALATED = "APPROVAL_ESCALATED"
    APPROVAL_DELEGATED = "APPROVAL_DELEGATED"
    APPROVAL_SUPERSEDED = "APPROVAL_SUPERSEDED"
    APPROVAL_POLICY_EVALUATED = "APPROVAL_POLICY_EVALUATED"
    APPROVAL_POLICY_FAILED = "APPROVAL_POLICY_FAILED"
    APPROVAL_EXECUTION_BLOCKED = "APPROVAL_EXECUTION_BLOCKED"
    APPROVAL_ACCESS_DENIED = "APPROVAL_ACCESS_DENIED"


class AuditEventRecord(BaseModel):
    """Immutable audit event record for persistence and structured logging.

    Contains only the minimum metadata for accountability.
    Clinical payload content is NEVER included.
    """

    model_config = ConfigDict(frozen=True, populate_by_name=True, extra="ignore")

    id: str | None = None
    event_type: AuditEventType
    actor_id: str | None = Field(
        default=None,
        description="User ID of the requester/actor. None for unauthenticated requests.",
    )
    user_id: str | None = None
    patient_id: str | None = None
    action: str | None = Field(
        default=None,
        description="The action attempted (e.g., 'clinical_record:read')",
    )
    resource_type: str | None = Field(
        default=None,
        description="Type of resource targeted (e.g., 'clinical_record')",
    )
    resource_id: str | None = Field(
        default=None,
        description="Identifier of the targeted resource (non-clinical ID only)",
    )
    outcome: str = Field(description="'ALLOW' or 'DENY'")
    reason_code: str | None = Field(
        default=None,
        description="Internal reason code for denials (e.g., 'CONSENT_REVOKED')",
    )
    request_id: str | None = Field(
        default=None,
        description="Correlation request ID from middleware",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of the event",
    )
    metadata: dict | None = Field(
        default=None,
        description="Optional minimal supplementary metadata. Must not contain PHI.",
    )

    @property
    def details(self) -> dict | None:
        """Alias for metadata for backwards compatibility."""
        return self.metadata


AuditRecord = AuditEventRecord


class AuditSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class AuditActor(BaseModel):
    model_config = ConfigDict(extra="ignore")

    actor_id: str
    role: Any = None
    organization_id: Optional[str] = None
    facility_id: Optional[str] = None
