"""Pydantic schemas for audit events.

Audit events are separate from application logs.
They record security/access decisions and consent lifecycle events.

CRITICAL — Audit events must NEVER contain:
- Clinical record content
- Diagnosis, symptoms, prescriptions
- Medication lists or medical history
- Passwords, tokens, or secrets
- PHI beyond minimum subject/actor identifiers
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, ConfigDict, Field


class AuditEventType(str, Enum):
    """Supported audit event type identifiers."""

    # Authorization events
    AUTHZ_ACCESS_GRANTED = "AUTHZ_ACCESS_GRANTED"
    AUTHZ_ACCESS_DENIED = "AUTHZ_ACCESS_DENIED"
    AUTHZ_PERMISSION_MISSING = "AUTHZ_PERMISSION_MISSING"
    AUTHZ_OWNERSHIP_FAILED = "AUTHZ_OWNERSHIP_FAILED"
    AUTHZ_RELATIONSHIP_FAILED = "AUTHZ_RELATIONSHIP_FAILED"

    # Consent lifecycle events
    CONSENT_CREATED = "CONSENT_CREATED"
    CONSENT_READ = "CONSENT_READ"
    CONSENT_REVOKED = "CONSENT_REVOKED"
    CONSENT_CHECK_PASSED = "CONSENT_CHECK_PASSED"
    CONSENT_CHECK_FAILED = "CONSENT_CHECK_FAILED"

    # Authentication events (mirrors Phase 2 logging for completeness)
    AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
    AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE"
    AUTH_REFRESH_SUCCESS = "AUTH_REFRESH_SUCCESS"
    AUTH_LOGOUT = "AUTH_LOGOUT"

    # Clinical record events (Phase 4)
    CLINICAL_RECORD_VIEWED = "CLINICAL_RECORD_VIEWED"
    PATIENT_PROFILE_UPDATED = "PATIENT_PROFILE_UPDATED"
    CLINICAL_HISTORY_CREATED = "CLINICAL_HISTORY_CREATED"
    CLINICAL_HISTORY_UPDATED = "CLINICAL_HISTORY_UPDATED"
    ALLERGY_CREATED = "ALLERGY_CREATED"
    ALLERGY_UPDATED = "ALLERGY_UPDATED"
    VITAL_RECORDED = "VITAL_RECORDED"
    ENCOUNTER_VIEWED = "ENCOUNTER_VIEWED"
    ENCOUNTER_CREATED = "ENCOUNTER_CREATED"
    CLINICAL_SUMMARY_VIEWED = "CLINICAL_SUMMARY_VIEWED"

    # Medical document events (Phase 5)
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_VIEWED = "DOCUMENT_VIEWED"
    DOCUMENT_DOWNLOAD_REQUESTED = "DOCUMENT_DOWNLOAD_REQUESTED"
    DOCUMENT_ARCHIVED = "DOCUMENT_ARCHIVED"
    DOCUMENT_PROCESSING_STARTED = "DOCUMENT_PROCESSING_STARTED"
    DOCUMENT_PROCESSING_COMPLETED = "DOCUMENT_PROCESSING_COMPLETED"
    DOCUMENT_PROCESSING_FAILED = "DOCUMENT_PROCESSING_FAILED"
    DOCUMENT_PROCESSING_RETRIED = "DOCUMENT_PROCESSING_RETRIED"
    DOCUMENT_EXTRACTION_CREATED = "DOCUMENT_EXTRACTION_CREATED"
    DOCUMENT_EXTRACTION_VIEWED = "DOCUMENT_EXTRACTION_VIEWED"

    # Prescription & Medication events (Phase 6)
    PRESCRIPTION_CREATED = "PRESCRIPTION_CREATED"
    PRESCRIPTION_VIEWED = "PRESCRIPTION_VIEWED"
    PRESCRIPTION_UPDATED = "PRESCRIPTION_UPDATED"
    PRESCRIPTION_NORMALIZATION_STARTED = "PRESCRIPTION_NORMALIZATION_STARTED"
    PRESCRIPTION_NORMALIZATION_COMPLETED = "PRESCRIPTION_NORMALIZATION_COMPLETED"
    PRESCRIPTION_NORMALIZATION_FAILED = "PRESCRIPTION_NORMALIZATION_FAILED"
    MEDICATION_CREATED = "MEDICATION_CREATED"
    MEDICATION_VIEWED = "MEDICATION_VIEWED"
    MEDICATION_UPDATED = "MEDICATION_UPDATED"
    MEDICATION_STATUS_CHANGED = "MEDICATION_STATUS_CHANGED"
    MEDICATION_CORRECTED = "MEDICATION_CORRECTED"

    # Medication Safety events (Phase 7)
    MEDICATION_SAFETY_CHECK_STARTED = "MEDICATION_SAFETY_CHECK_STARTED"
    MEDICATION_SAFETY_CHECK_COMPLETED = "MEDICATION_SAFETY_CHECK_COMPLETED"
    MEDICATION_SAFETY_CHECK_FAILED = "MEDICATION_SAFETY_CHECK_FAILED"
    MEDICATION_SAFETY_RESULT_VIEWED = "MEDICATION_SAFETY_RESULT_VIEWED"

    # Triage & SBAR events (Phase 8)
    SYMPTOM_INTAKE_CREATED = "SYMPTOM_INTAKE_CREATED"
    SYMPTOM_INTAKE_VIEWED = "SYMPTOM_INTAKE_VIEWED"
    TRIAGE_ASSESSMENT_STARTED = "TRIAGE_ASSESSMENT_STARTED"
    TRIAGE_ASSESSMENT_COMPLETED = "TRIAGE_ASSESSMENT_COMPLETED"
    TRIAGE_ASSESSMENT_FAILED = "TRIAGE_ASSESSMENT_FAILED"
    TRIAGE_REASSESSMENT_CREATED = "TRIAGE_REASSESSMENT_CREATED"
    SBAR_CREATED = "SBAR_CREATED"
    SBAR_VIEWED = "SBAR_VIEWED"
    SBAR_REGENERATED = "SBAR_REGENERATED"

    # Care Plan & Discharge events (Phase 9)
    DISCHARGE_EXTRACTION_STARTED = "DISCHARGE_EXTRACTION_STARTED"
    DISCHARGE_EXTRACTION_COMPLETED = "DISCHARGE_EXTRACTION_COMPLETED"
    DISCHARGE_EXTRACTION_FAILED = "DISCHARGE_EXTRACTION_FAILED"
    DISCHARGE_VERIFIED = "DISCHARGE_VERIFIED"
    CARE_PLAN_CREATED = "CARE_PLAN_CREATED"
    CARE_PLAN_UPDATED = "CARE_PLAN_UPDATED"
    CARE_PLAN_VIEWED = "CARE_PLAN_VIEWED"
    CARE_PLAN_STATUS_CHANGED = "CARE_PLAN_STATUS_CHANGED"

    # Doctor Clinical Workflow events (Phase 10)
    CLINICAL_NOTE_CREATED = "CLINICAL_NOTE_CREATED"
    CLINICAL_NOTE_UPDATED = "CLINICAL_NOTE_UPDATED"
    CLINICAL_NOTE_SIGNED = "CLINICAL_NOTE_SIGNED"
    CLINICAL_NOTE_VIEWED = "CLINICAL_NOTE_VIEWED"
    CLINICAL_ASSESSMENT_CREATED = "CLINICAL_ASSESSMENT_CREATED"
    CLINICAL_ASSESSMENT_UPDATED = "CLINICAL_ASSESSMENT_UPDATED"
    CLINICAL_ASSESSMENT_FINALIZED = "CLINICAL_ASSESSMENT_FINALIZED"
    CLINICAL_ASSESSMENT_VIEWED = "CLINICAL_ASSESSMENT_VIEWED"
    CLINICAL_PLAN_CREATED = "CLINICAL_PLAN_CREATED"
    CLINICAL_PLAN_UPDATED = "CLINICAL_PLAN_UPDATED"
    CLINICAL_PLAN_FINALIZED = "CLINICAL_PLAN_FINALIZED"
    CLINICAL_PLAN_VIEWED = "CLINICAL_PLAN_VIEWED"
    CLINICAL_WORKSPACE_ACCESSED = "CLINICAL_WORKSPACE_ACCESSED"

    # Hospital & Organization Network events (Phase 11)
    ORGANIZATION_LIST_VIEWED = "ORGANIZATION_LIST_VIEWED"
    ORGANIZATION_VIEWED = "ORGANIZATION_VIEWED"
    FACILITY_LIST_VIEWED = "FACILITY_LIST_VIEWED"
    FACILITY_VIEWED = "FACILITY_VIEWED"
    DEPARTMENT_LIST_VIEWED = "DEPARTMENT_LIST_VIEWED"
    CLINICIAN_ORGANIZATIONS_VIEWED = "CLINICIAN_ORGANIZATIONS_VIEWED"
    CLINICIAN_FACILITIES_VIEWED = "CLINICIAN_FACILITIES_VIEWED"
    ORGANIZATION_CONTEXT_VIEWED = "ORGANIZATION_CONTEXT_VIEWED"
    FACILITY_CONTEXT_VIEWED = "FACILITY_CONTEXT_VIEWED"

    # Facility Discovery & Transfer events (Phase 12)
    FACILITY_DISCOVERY_STARTED = "FACILITY_DISCOVERY_STARTED"
    FACILITY_DISCOVERY_COMPLETED = "FACILITY_DISCOVERY_COMPLETED"
    FACILITY_DISCOVERY_FAILED = "FACILITY_DISCOVERY_FAILED"
    FACILITY_VIEWED_FOR_TRANSFER = "FACILITY_VIEWED_FOR_TRANSFER"
    TRANSFER_CREATED = "TRANSFER_CREATED"
    TRANSFER_VIEWED = "TRANSFER_VIEWED"
    TRANSFER_STATUS_UPDATED = "TRANSFER_STATUS_UPDATED"
    TRANSFER_ACCEPTED = "TRANSFER_ACCEPTED"
    TRANSFER_DECLINED = "TRANSFER_DECLINED"
    TRANSFER_CANCELLED = "TRANSFER_CANCELLED"
    TRANSFER_COMPLETED = "TRANSFER_COMPLETED"
    TRANSFER_FAILED = "TRANSFER_FAILED"
    TRANSFER_CLINICAL_CONTEXT_SHARED = "TRANSFER_CLINICAL_CONTEXT_SHARED"
    TRANSFER_SBAR_ATTACHED = "TRANSFER_SBAR_ATTACHED"

    # Interoperability & Healthcare Data Exchange events (Phase 13)
    INTEROPERABILITY_IMPORT_STARTED = "INTEROPERABILITY_IMPORT_STARTED"
    INTEROPERABILITY_IMPORT_COMPLETED = "INTEROPERABILITY_IMPORT_COMPLETED"
    INTEROPERABILITY_IMPORT_FAILED = "INTEROPERABILITY_IMPORT_FAILED"
    INTEROPERABILITY_IMPORT_REJECTED = "INTEROPERABILITY_IMPORT_REJECTED"
    INTEROPERABILITY_EXPORT_STARTED = "INTEROPERABILITY_EXPORT_STARTED"
    INTEROPERABILITY_EXPORT_COMPLETED = "INTEROPERABILITY_EXPORT_COMPLETED"
    INTEROPERABILITY_EXPORT_FAILED = "INTEROPERABILITY_EXPORT_FAILED"
    INTEROPERABILITY_RESOURCE_VIEWED = "INTEROPERABILITY_RESOURCE_VIEWED"
    EXTERNAL_IDENTITY_RESOLVED = "EXTERNAL_IDENTITY_RESOLVED"
    EXTERNAL_IDENTITY_UNRESOLVED = "EXTERNAL_IDENTITY_UNRESOLVED"
    INTEROPERABILITY_DATA_SHARED = "INTEROPERABILITY_DATA_SHARED"
    INTEROPERABILITY_VERIFICATION_REQUIRED = "INTEROPERABILITY_VERIFICATION_REQUIRED"

    # AI & Intelligence Layer events (Phase 14)
    AI_TASK_CREATED = "AI_TASK_CREATED"
    AI_TASK_STARTED = "AI_TASK_STARTED"
    AI_TASK_COMPLETED = "AI_TASK_COMPLETED"
    AI_TASK_FAILED = "AI_TASK_FAILED"
    AI_TASK_RETRIED = "AI_TASK_RETRIED"
    AI_OUTPUT_VALIDATION_FAILED = "AI_OUTPUT_VALIDATION_FAILED"
    AI_GROUNDING_VALIDATION_FAILED = "AI_GROUNDING_VALIDATION_FAILED"
    AI_RESULT_VIEWED = "AI_RESULT_VIEWED"
    AI_RESULT_REGENERATED = "AI_RESULT_REGENERATED"
    AI_RESULT_REVIEW_REQUIRED = "AI_RESULT_REVIEW_REQUIRED"
    AI_RESULT_VERIFIED = "AI_RESULT_VERIFIED"
    AI_RESULT_CORRECTED = "AI_RESULT_CORRECTED"
    AI_RESULT_REJECTED = "AI_RESULT_REJECTED"
    AI_PROVIDER_ERROR = "AI_PROVIDER_ERROR"
    AI_PROVIDER_TIMEOUT = "AI_PROVIDER_TIMEOUT"
    AI_PROMPT_VERSION_USED = "AI_PROMPT_VERSION_USED"

    # Asynchronous Workflow & Event-Driven execution events (Phase 22)
    JOB_CREATED = "JOB_CREATED"
    JOB_QUEUED = "JOB_QUEUED"
    JOB_STARTED = "JOB_STARTED"
    JOB_COMPLETED = "JOB_COMPLETED"
    JOB_FAILED = "JOB_FAILED"
    JOB_RETRY_SCHEDULED = "JOB_RETRY_SCHEDULED"
    JOB_CANCELLED = "JOB_CANCELLED"
    EVENT_PUBLISHED = "EVENT_PUBLISHED"
    EVENT_CONSUMED = "EVENT_CONSUMED"
    EVENT_DUPLICATE_IGNORED = "EVENT_DUPLICATE_IGNORED"
    WORKFLOW_STARTED = "WORKFLOW_STARTED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
    WORKFLOW_FAILED = "WORKFLOW_FAILED"

    # Advanced Data Privacy, Lifecycle & Governance events (Phase 24)
    PRIVACY_POLICY_CHECKED = "PRIVACY_POLICY_CHECKED"
    SENSITIVE_DATA_ACCESSED = "SENSITIVE_DATA_ACCESSED"
    DATA_EXPORT_REQUESTED = "DATA_EXPORT_REQUESTED"
    DATA_EXPORT_COMPLETED = "DATA_EXPORT_COMPLETED"
    DATA_EXPORT_FAILED = "DATA_EXPORT_FAILED"
    DATA_EXPORT_DOWNLOADED = "DATA_EXPORT_DOWNLOADED"
    DATA_EXPORT_EXPIRED = "DATA_EXPORT_EXPIRED"
    RETENTION_EVALUATED = "RETENTION_EVALUATED"
    RESOURCE_ARCHIVE_STARTED = "RESOURCE_ARCHIVE_STARTED"
    RESOURCE_ARCHIVED = "RESOURCE_ARCHIVED"
    RESOURCE_DELETION_REQUESTED = "RESOURCE_DELETION_REQUESTED"
    RESOURCE_DELETION_COMPLETED = "RESOURCE_DELETION_COMPLETED"
    RESOURCE_DELETION_FAILED = "RESOURCE_DELETION_FAILED"
    DEIDENTIFICATION_STARTED = "DEIDENTIFICATION_STARTED"
    DEIDENTIFICATION_COMPLETED = "DEIDENTIFICATION_COMPLETED"
    PSEUDONYMIZATION_COMPLETED = "PSEUDONYMIZATION_COMPLETED"
    PRIVACY_POLICY_DENIED = "PRIVACY_POLICY_DENIED"

    # Feature Flags, Configuration Governance & Controlled Rollout (Phase 25)
    CONFIGURATION_CREATED = "CONFIGURATION_CREATED"
    CONFIGURATION_UPDATED = "CONFIGURATION_UPDATED"
    CONFIGURATION_DELETED = "CONFIGURATION_DELETED"
    FEATURE_FLAG_ENABLED = "FEATURE_FLAG_ENABLED"
    FEATURE_FLAG_DISABLED = "FEATURE_FLAG_DISABLED"
    FEATURE_FLAG_ROLLOUT_CHANGED = "FEATURE_FLAG_ROLLOUT_CHANGED"
    PROVIDER_CONFIGURATION_CHANGED = "PROVIDER_CONFIGURATION_CHANGED"
    KILL_SWITCH_ENABLED = "KILL_SWITCH_ENABLED"
    KILL_SWITCH_DISABLED = "KILL_SWITCH_DISABLED"
    CONFIGURATION_VALIDATION_FAILED = "CONFIGURATION_VALIDATION_FAILED"

    # Data Quality, Clinical Record Integrity & Reconciliation events (Phase 26)
    DATA_QUALITY_CHECK_STARTED = "DATA_QUALITY_CHECK_STARTED"
    DATA_QUALITY_CHECK_COMPLETED = "DATA_QUALITY_CHECK_COMPLETED"
    DATA_QUALITY_CHECK_FAILED = "DATA_QUALITY_CHECK_FAILED"
    DATA_QUALITY_FINDING_CREATED = "DATA_QUALITY_FINDING_CREATED"
    DATA_QUALITY_FINDING_VIEWED = "DATA_QUALITY_FINDING_VIEWED"
    DATA_QUALITY_REVIEW_STARTED = "DATA_QUALITY_REVIEW_STARTED"
    DATA_QUALITY_FINDING_RESOLVED = "DATA_QUALITY_FINDING_RESOLVED"
    DATA_QUALITY_FINDING_REJECTED = "DATA_QUALITY_FINDING_REJECTED"
    DUPLICATE_DETECTED = "DUPLICATE_DETECTED"
    DUPLICATE_CONFIRMED = "DUPLICATE_CONFIRMED"
    DUPLICATE_REJECTED = "DUPLICATE_REJECTED"
    RECONCILIATION_STARTED = "RECONCILIATION_STARTED"
    RECONCILIATION_COMPLETED = "RECONCILIATION_COMPLETED"
    RECONCILIATION_FAILED = "RECONCILIATION_FAILED"
    RECONCILIATION_RESOLVED = "RECONCILIATION_RESOLVE"
    CLINICAL_RECORD_CORRECTED = "CLINICAL_RECORD_CORRECTED"
    CLINICAL_RECORD_SUPERSEDED = "CLINICAL_RECORD_SUPERSEDED"
    EXTERNAL_DATA_CONFLICT_DETECTED = "EXTERNAL_DATA_CONFLICT_DETECTED"

    # Administration, Support Operations & Controlled Backoffice (Phase 27)
    ADMIN_SYSTEM_STATUS_VIEWED = "ADMIN_SYSTEM_STATUS_VIEWED"
    ADMIN_JOB_VIEWED = "ADMIN_JOB_VIEWED"
    ADMIN_JOB_RETRIED = "ADMIN_JOB_RETRIED"
    ADMIN_JOB_CANCELLED = "ADMIN_JOB_CANCELLED"
    ADMIN_INTEGRATION_VIEWED = "ADMIN_INTEGRATION_VIEWED"
    ADMIN_INTEGRATION_TESTED = "ADMIN_INTEGRATION_TESTED"
    ADMIN_INCIDENT_CREATED = "ADMIN_INCIDENT_CREATED"
    ADMIN_INCIDENT_UPDATED = "ADMIN_INCIDENT_UPDATED"
    ADMIN_INCIDENT_RESOLVED = "ADMIN_INCIDENT_RESOLVED"
    ADMIN_AUDIT_VIEWED = "ADMIN_AUDIT_VIEWED"
    ADMIN_SECURITY_EVENT_VIEWED = "ADMIN_SECURITY_EVENT_VIEWED"
    ADMIN_DATA_QUALITY_VIEWED = "ADMIN_DATA_QUALITY_VIEWED"
    ADMIN_SUPPORT_LOOKUP = "ADMIN_SUPPORT_LOOKUP"
    ADMIN_CONFIGURATION_VIEWED = "ADMIN_CONFIGURATION_VIEWED"
    ADMIN_CONFIGURATION_CHANGED = "ADMIN_CONFIGURATION_CHANGED"

    # Notification, Communication & Event Delivery System (Phase 29)
    NOTIFICATION_CREATED = "NOTIFICATION_CREATED"
    NOTIFICATION_QUEUED = "NOTIFICATION_QUEUED"
    NOTIFICATION_SENT = "NOTIFICATION_SENT"
    NOTIFICATION_DELIVERED = "NOTIFICATION_DELIVERED"
    NOTIFICATION_FAILED = "NOTIFICATION_FAILED"
    NOTIFICATION_RETRY_STARTED = "NOTIFICATION_RETRY_STARTED"
    NOTIFICATION_CANCELLED = "NOTIFICATION_CANCELLED"
    NOTIFICATION_READ = "NOTIFICATION_READ"
    NOTIFICATION_DISMISSED = "NOTIFICATION_DISMISSED"
    NOTIFICATION_PREFERENCE_CHANGED = "NOTIFICATION_PREFERENCE_CHANGED"
    NOTIFICATION_PROVIDER_TESTED = "NOTIFICATION_PROVIDER_TESTED"
    NOTIFICATION_BULK_OPERATION_STARTED = "NOTIFICATION_BULK_OPERATION_STARTED"
    NOTIFICATION_BULK_OPERATION_COMPLETED = "NOTIFICATION_BULK_OPERATION_COMPLETED"



class AuditEventRecord(BaseModel):
    """Immutable audit event record for persistence and structured logging.

    Contains only the minimum metadata for accountability.
    Clinical payload content is NEVER included.
    """

    model_config = ConfigDict(frozen=True, populate_by_name=True, extra="ignore")

    id: str | None = None
    event_type: AuditEventType
    actor_id: str | None = Field(
        default=None,
        description="User ID of the requester/actor. None for unauthenticated requests.",
    )
    user_id: str | None = None
    patient_id: str | None = None
    action: str | None = Field(
        default=None,
        description="The action attempted (e.g., 'clinical_record:read')",
    )
    resource_type: str | None = Field(
        default=None,
        description="Type of resource targeted (e.g., 'clinical_record')",
    )
    resource_id: str | None = Field(
        default=None,
        description="Identifier of the targeted resource (non-clinical ID only)",
    )
    outcome: str = Field(description="'ALLOW' or 'DENY'")
    reason_code: str | None = Field(
        default=None,
        description="Internal reason code for denials (e.g., 'CONSENT_REVOKED')",
    )
    request_id: str | None = Field(
        default=None,
        description="Correlation request ID from middleware",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of the event",
    )
    metadata: dict | None = Field(
        default=None,
        description="Optional minimal supplementary metadata. Must not contain PHI.",
    )

    @property
    def details(self) -> dict | None:
        """Alias for metadata for backwards compatibility."""
        return self.metadata


AuditRecord = AuditEventRecord


class AuditSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class AuditActor(BaseModel):
    model_config = ConfigDict(extra="ignore")

    actor_id: str
    role: Any = None
    organization_id: Optional[str] = None
    facility_id: Optional[str] = None
